from app.api.v1 import auth
from app.api.v1 import users
from app.api.v1 import customers
from app.api.v1 import twins
from app.api.v1 import events
from app.api.v1 import campaigns
from app.api.v1 import simulations
from app.api.v1 import recommendations
from app.api.v1 import notifications
from app.api.v1 import analytics
from app.api.v1 import segments
